spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:brokerage-db}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    sql:
      init:
        mode: always
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}